package es.udc.OpenHope.enums;

public enum SortCriteria {
  NAME_ASC,
  NAME_DESC,
  START_DATE_ASC,
  START_DATE_DESC,
  END_DATE_ASC,
  END_DATE_DESC,
  TARGET_AMOUNT_ASC,
  TARGET_AMOUNT_DESC,
  MIN_DONATION_ASC,
  MIN_DONATION_DESC,
  CLOSEST_TO_GOAL,
  FARTHEST_FROM_GOAL
}
